### ISSUE TITLE
Site Just stopped working

### ISSUE THREAD

**Issue by HabsburgVonHabsburg** [Tyson3101/Medal-Bypass#2]
It could just be a bug on my end, but I was uploading clips and got through a bunch until eventually every clip I uploaded came up with the wait error, or saying I put the URL in wrong. I've waited multiple hours and even tried editing and revising the clips but they still won't upload to the website. Are there any quick fixes I can try or am I just out of luck. 

Thanks for this website by the way, it's been incredibly helpful!

**Comment by Tyson3101** [comment]
Hmm yes, I am getting this too
Thanks a lot for the heads up, I will take a look and see what the issues could be.

And I am glad to hear that this site has been useful for you

**Comment by Tyson3101** [comment]
Damn the reason for the error was a bit silly. But I do believe I have fixed it.
If you face any other issues just let me know. And thanks again for the heads up
