### ISSUE TITLE
Medal Bypass Stopped Working Again

### ISSUE THREAD

**Issue by HabsburgVonHabsburg** [Tyson3101/Medal-Bypass#3]
Hello Again!

Thanks for the fix last time, it worked really well, in fact the website was working almost instantly after you fixed it. I saw the edit you made saying Medal was changing stuff around so the website wasn't working, but it still doesn't work now that the error is gone. I just wanted to let you know and I appreciate all of the work you have put into this. It's really been helping me a lot so thank you for that!

**Comment by Tyson3101** [comment]
Hey thanks for the issue, I believe I have finally fixed it. 
And I am glad that you find this helpful (it has been very helpful for me too lol).
