### ISSUE TITLE
[question for dev]

### ISSUE THREAD

**Issue by dothenotive** [Tyson3101/Medal-Bypass#4]
Whenever I try to make a POST request for the https://us-central1-medalbypass.cloudfunctions.net/medalwatermark/ site, i am getting valid set to false, no matter what i change. Can you make an API, or, allow others to make POST requests for the website?

**Comment by Tyson3101** [comment]
Hi I don't see why you shouldn't be able to make a POST request as there is no CORS blocking it. 
What does your request look like?
Also, if you want a potential workaround, you can do a GET request by adding a query parameter of ?url=encodedURL
For example, https://us-central1-medalbypass.cloudfunctions.net/medalwatermark?url=https%3A%2F%2Fmedal.tv%2Fgames%2Frocket-league%2Fclips%2FZIUOFgLFIX9ug%2FcYefuGD4vAQJ%3Finvite%3Dcr-MSxNbFAsMTAxMjA1MjMs

**Comment by Tyson3101** [comment]
Np, glad it helped you out
